import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs) {
        //TODO: write code here
        List<Item> itemList = itemRepository.findAll();
        List<SalesPromotion> salesPromotionList = salesPromotionRepository.findAll();

//      [[id, number], [id, number]]
        ArrayList<ArrayList<String>> orderInfo = new ArrayList<>();
        for (String s : inputs) {
            String[] info = s.split("x");
            ArrayList<String> list = new ArrayList<>();
            list.add(info[0].trim());
            list.add(info[1].trim());
            orderInfo.add(list);
        }
//       [[name, price, number], [name, price, number]]
        ArrayList<ArrayList<String>> orderInfo2 = new ArrayList<>();
        for (ArrayList<String> list : orderInfo) {
            String id = list.get(0);
            String num = list.get(1);
            for (Item item : itemList) {
                if (item.getId().equals(id)) {
                    ArrayList<String> list1 = new ArrayList<>();
                    list1.add(item.getName());
                    list1.add(String.valueOf(item.getPrice()));
                    list1.add(String.valueOf(num));
                    orderInfo2.add(list1);
                    break;
                }
            }
        }
//        30-6优惠
        int total1 = 0;
//        半价优惠
        int total2 = 0;
        int saving = 0;
        boolean flag = true;
        String b_c = "Braised chicken";
        String c_n = "Cold noodles";

        for (ArrayList<String> item : orderInfo2) {

            if (item.get(0).equals(b_c) || item.get(0).equals(c_n)) {
                saving += (int)(Double.valueOf(item.get(1)) * Double.valueOf(item.get(2)) / 2);
                total2 += (int)(Double.valueOf(item.get(1)) * Double.valueOf(item.get(2)) / 2);
                flag = false;
            } else {
                total2 += (int)(Double.valueOf(item.get(1)) * Double.valueOf(item.get(2)));
            }
            total1 += (int) (Double.valueOf(item.get(1)) * Double.valueOf(item.get(2)));

        }
        if (total1 >= 30) {
            total1 -= 6;
            flag = false;
        }
        String result = "============= Order details =============\n";
        for (ArrayList<String> item : orderInfo2) {
            result += item.get(0) + " x " + item.get(2) + " = " + (int)(Double.valueOf(item.get(1)) * Double.valueOf(item.get(2))) + " yuan\n";
        }
        result += "-----------------------------------\n";

        if (false) {


                    result += "Total：" + total1 + " yuan\n" +
                    "===================================";

        } else if (total1 > total2){
            result += "Promotion used:\n" +
                    "Half price for certain dishes (Braised chicken，Cold noodles)，saving " + saving+" yuan\n" +
                    "-----------------------------------\n" +
                    "Total：" + total2 + " yuan\n" +
                    "===================================";

        }else {
            result +=   "Promotion used:\n" +
                    "满30减6 yuan，saving 6 yuan\n" +
                    "-----------------------------------\n" +
                    "Total：" + total1 + " yuan\n" +
                    "===================================";



        }
        return  result;
    }
}
